#!/bin/bash

# Abfrage der Webservices von myspoho (HISinOne) unter Linux
# Die nächsten 2 Zeilen müssen noch geändert werden.
# Die Infos befinden sich bei https://elearning.dshs-koeln.de/nc
# in Notes->HISinOne | hiszugang.txt
# Nach der Anfrage bei einem Webservice befindet sich dann das Ergebnis
# zur weiteren Verarbeitung in /dev/shm/response.xml
# Die Benutzung ist dann wie folgt 
# his Service Operation "variable1:value variable2:value"
# z.B. für ID's aller Kurse des Sommersemester 2022:
# his PlanelementService findPlanelementOfEvent "termYear:2022 termTypeValueId:30"
username="username" # <- noch ändern
password="password" # <- noch ändern
service="$1"
operation="$2"
input="$3" # Variable:Value, mehrere mit leerzeichen getrennt
url="https://myspoho-test5.dshs-koeln.de/qisserver/services2/" # <- eventuell später noch ändern
# Hier ist auch die Beschreibung der API's zu finden

parameter=""
for in in $input
do
	par=`echo $in | awk -F ":" '{print $1;}'`
	val=`echo $in | awk -F ":" '{print $2;}'`
	parameter+="<$par>$val</$par>"
done
servicerequesta="<"
servicerequesta+=$service
servicerequesta+=":"
servicerequesta+=$operation
servicerequesta+=">"
servicerequestb="</"$service":"$operation">"
soapaction="SOAPAction: \""$service":"$operation"\""
request="  <soapenv:Envelope 
    xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" 
    xmlns:"$service"=\"https://myspoho-test5.dshs-koeln.de/webservice/qisserver/services2/"
request+=$service
request+="\">
    <soapenv:Header>
    <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\" >
    <wsse:UsernameToken>
    <wsse:Username>"$username"</wsse:Username>
    <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">"$password"</wsse:Password>
    </wsse:UsernameToken>
    </wsse:Security>
    </soapenv:Header>
    <soapenv:Body>"
request+=$servicerequesta
request+=$parameter
request+=$servicerequestb
request+="</soapenv:Body>
  </soapenv:Envelope>"
echo $request > /dev/shm/request.xml
wget -q --no-check-certificate --post-file=/dev/shm/request.xml --header="Content-Type: text/xml" --header="$soapaction" $url -O /dev/shm/response.xml
