#!/bin/bash

source /usr/local/bin/mconfig
service="$1"
operation="$2"
input="$3" # Feldname:Value, mehrere mit leerzeichen getrennt | Sondefall z.B languages:de,en
parameter=""
for in in $input
do
	anzahl=`echo $in | awk -F ":" '{print NF;}'`
	case $anzahl in
	    2)
		par=`echo $in | awk -F ":" '{print $1;}'`
		val=`echo $in | awk -F ":" '{print $2;}'`
		parameter+="<$par>$val</$par>"
		;;
	    3)
		para=`echo $in | awk -F ":" '{print $1;}'`
		parb=`echo $in | awk -F ":" '{print $2;}'`
		val=`echo $in | awk -F ":" '{print $3;}'`
		parameter+="<$para><$parb>$val</$parb></$para>"
		;;
	esac
done
servicerequesta="<"
servicerequesta+=$service
servicerequesta+=":"
servicerequesta+=$operation
servicerequesta+=">"
servicerequestb="</"$service":"$operation">"
soapaction="SOAPAction: \""$service":"$operation"\""
request="  <soapenv:Envelope 
    xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" 
    xmlns:"$service"=\""$url
request+=$service
request+="\">
    <soapenv:Header>
    <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\" >
    <wsse:UsernameToken>
    <wsse:Username>"$username"</wsse:Username>
    <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">"$password"</wsse:Password>
    </wsse:UsernameToken>
    </wsse:Security>
    </soapenv:Header>
    <soapenv:Body>"
request+=$servicerequesta
request+=$parameter
request+=$servicerequestb
request+="</soapenv:Body>
  </soapenv:Envelope>"
echo $request > /dev/shm/request.xml
curl -s -k -X POST $url \
  -H "Content-Type: text/xml" \
  -H "$soapaction" \
  -d @/dev/shm/request.xml -o /dev/shm/response.xml
check=`grep 'faultcode' /dev/shm/response.xml | wc -l`
if [ $check -gt 0 ]; then
    fcode=`awk -F "<faultcode>" '{print $2;}' /dev/shm/response.xml | awk -F "</faultcode>" '{print $1;}'`
    echo "Achtung!: $fcode" >> /dev/shm/hisfehler
fi
check=`grep -i 'exception' /dev/shm/response.xml | wc -l`
if [ $check -gt 0 ]; then
    fcode=`grep -i 'exception' /dev/shm/response.xml | head -n1`
    echo "Achtung!: $fcode" >> /dev/shm/hisfehler
fi
chmod 666 /dev/shm/response.xml /dev/shm/request.xml
