#!/bin/bash

jahr="$1"
semester="$2" # wise oder sose
case $semester in
    sose)
	sem="30"
	;;
    wise)
	sem="31"
	;;
esac
his PlanelementService findPlanelementOfEvent "termYear:$jahr termTypeValueId:$sem"
cat /dev/shm/response.xml | sed 's/<his:id>/\n<his:id>/g' | sed 's/>/</g' | awk -F "<" '{print $3;}' > /dev/shm/tt
while read line
do
    # planelementid;unitid;Kursname;editingstatusid;parallelgrouppe
    his PlanelementService readPlanelementOfEvent "planelementId:$line"
    cat /dev/shm/response.xml | sed 's/termYear><his:defaulttext/termYear><his:deaulttext/' | \
    sed 's/groupId><his:default/groupId><his:deault/' | \
    sed 's/<his:/\n<his:/g' | grep "<his:unitId\|<his:planelementId\|<his:defaulttext\|editingStatusId\|<his:parallelgroupId" | \
    tr -d '\r\n' | sed 's/>/</g' | awk -F "<" '{print $3";"$7";"$11";"$15";"$19;}'
done < /dev/shm/tt
